/**
 * Demo seed configuration for the Duneworks Productions CRM.
 *
 * Keep credentials and starter records here — never hard-code them in UI components.
 */

export const DEMO_ADMIN = {
  id: "user_admin",
  name: "Mara Ellison",
  email: "Duneworksstudios@gmail.com",
  password: "Duneworks123",
  role: "Admin" as const,
};

export const DEMO_TEAM = [
  {
    id: "user_manager",
    name: "Caleb Ward",
    email: "caleb.ward@duneworks.studio",
    password: "StudioLead#44",
    role: "Manager" as const,
  },
  {
    id: "user_editor",
    name: "Sienna Okonkwo",
    email: "sienna.okonkwo@duneworks.studio",
    password: "EditBay#18",
    role: "Editor" as const,
  },
  {
    id: "user_viewer",
    name: "Jonah Reeves",
    email: "jonah.reeves@duneworks.studio",
    password: "WatchCut#07",
    role: "Viewer" as const,
  },
] as const;

export const DEFAULT_PIPELINE_STAGES = [
  { id: "stage_possible", name: "Possible Clients", slug: "possible-clients", color: "#c4b49a", sortOrder: 0, kind: "possible" },
  { id: "stage_contacted", name: "Contacted", slug: "contacted", color: "#8fa6c2", sortOrder: 1, kind: "contacted" },
  { id: "stage_demo", name: "Demo Scheduled", slug: "demo-scheduled", color: "#c9a45c", sortOrder: 2, kind: "demo" },
  { id: "stage_discussion", name: "In Discussion", slug: "in-discussion", color: "#b08968", sortOrder: 3, kind: "discussion" },
  { id: "stage_trial", name: "Trial", slug: "trial", color: "#7d9b76", sortOrder: 4, kind: "trial" },
  { id: "stage_paid", name: "Paid Client", slug: "paid-client", color: "#d4c4a8", sortOrder: 5, kind: "paid" },
  { id: "stage_denied", name: "Denied", slug: "denied", color: "#8a5a52", sortOrder: 6, kind: "denied" },
] as const;

export const DEMO_COMPANIES = [
  {
    id: "co_amberline",
    clientNumber: "DW-1024",
    company: "Amberline Records",
    industry: "Music",
    name: "Lila Voss",
    email: "lila@amberlinerecords.com",
    phone: "(323) 555-0142",
    potentialValue: 28000,
    source: "Referral",
    assignedUserId: "user_manager",
    stageId: "stage_possible",
    tags: ["Music Video"],
    notes: "Asked for a three-song visual package for the autumn release.",
    lastNote: "Warm intro from a mixer we worked with last spring.",
    createdAt: "2026-07-12",
  },
  {
    id: "co_northglass",
    clientNumber: "DW-1025",
    company: "Northglass Hotels",
    industry: "Hospitality",
    name: "Owen Hart",
    email: "owen.hart@northglass.com",
    phone: "(206) 555-0194",
    potentialValue: 64000,
    source: "Website",
    assignedUserId: "user_admin",
    stageId: "stage_contacted",
    tags: ["Brand Campaign"],
    notes: "Wants a cinematic property film for the Seattle flagship.",
    lastNote: "Sent a lookbook and waiting on brand guidelines.",
    createdAt: "2026-07-18",
  },
  {
    id: "co_redcedar",
    clientNumber: "DW-1026",
    company: "Redcedar Athletics",
    industry: "Sport",
    name: "Priya Nair",
    email: "priya@redcedar.co",
    phone: "(415) 555-0177",
    potentialValue: 41000,
    source: "Instagram",
    assignedUserId: "user_editor",
    stageId: "stage_demo",
    tags: ["Commercial"],
    notes: "Product launch spots for the trail-running line.",
    lastNote: "Demo booked for Thursday afternoon on the lot.",
    createdAt: "2026-07-22",
  },
  {
    id: "co_harbor",
    clientNumber: "DW-1027",
    company: "Harbor & Vine",
    industry: "Events",
    name: "Tomas Hale",
    email: "tomas@harborandvine.com",
    phone: "(707) 555-0118",
    potentialValue: 18500,
    source: "Cold outreach",
    assignedUserId: "user_manager",
    stageId: "stage_discussion",
    tags: ["Event"],
    notes: "Harvest dinner series coverage across three vineyards.",
    lastNote: "Comparing a two-camera vs three-camera package.",
    createdAt: "2026-07-28",
  },
  {
    id: "co_kiteloom",
    clientNumber: "DW-1028",
    company: "Kite & Loom",
    industry: "Fashion",
    name: "Elena Ruiz",
    email: "elena@kiteandloom.com",
    phone: "(213) 555-0160",
    potentialValue: 22000,
    source: "Repeat inquiry",
    assignedUserId: "user_editor",
    stageId: "stage_trial",
    tags: ["Brand Campaign"],
    notes: "Short lookbook film; trial edit due next week.",
    lastNote: "They liked the desert palette test stills.",
    createdAt: "2026-08-01",
  },
  {
    id: "co_solstice",
    clientNumber: "DW-1029",
    company: "Solstice Pictures",
    industry: "Film",
    name: "Adrian Cole",
    email: "adrian@solsticepictures.tv",
    phone: "(310) 555-0129",
    potentialValue: 92000,
    source: "Referral",
    assignedUserId: "user_admin",
    stageId: "stage_paid",
    tags: ["Film"],
    notes: "Narrative short, principal photography in October.",
    lastNote: "Deposit received. Locking the Palmdale locations.",
    createdAt: "2026-06-20",
  },
  {
    id: "co_ironbark",
    clientNumber: "DW-1030",
    company: "Ironbark Distilling",
    industry: "Beverage",
    name: "Greta Lang",
    email: "greta@ironbarkdistilling.com",
    phone: "(512) 555-0188",
    potentialValue: 15000,
    source: "Cold outreach",
    assignedUserId: "user_manager",
    stageId: "stage_denied",
    tags: ["Commercial"],
    notes: "Passed for now; internal team is cutting a stills campaign.",
    lastNote: "Asked to check back after the holiday bottle drop.",
    createdAt: "2026-06-14",
    deniedReason: "Budget parked until Q1 bottle launch.",
  },
  {
    id: "co_velvet",
    clientNumber: "DW-1031",
    company: "Velvet Current Radio",
    industry: "Audio",
    name: "Naomi Park",
    email: "naomi@velvetcurrent.fm",
    phone: "(347) 555-0133",
    potentialValue: 12000,
    source: "Instagram",
    assignedUserId: "user_viewer",
    stageId: "stage_contacted",
    tags: ["Event"],
    notes: "Live session films for the late-night show.",
    lastNote: "Sent rates for a four-episode package.",
    createdAt: "2026-08-04",
  },
  {
    id: "co_lumenforge",
    clientNumber: "DW-1032",
    company: "Lumenforge Labs",
    industry: "Technology",
    name: "Owen Drake",
    email: "owen@lumenforge.io",
    phone: "(650) 555-0155",
    potentialValue: 73000,
    source: "Website",
    assignedUserId: "user_admin",
    stageId: "stage_discussion",
    tags: ["Commercial"],
    notes: "Hardware launch film plus two cutdowns.",
    lastNote: "Legal is reviewing the usage window.",
    createdAt: "2026-08-06",
  },
  {
    id: "co_saltmarsh",
    clientNumber: "DW-1033",
    company: "Saltmarsh Events",
    industry: "Festivals",
    name: "Imani Brooks",
    email: "imani@saltmarshevents.com",
    phone: "(843) 555-0104",
    potentialValue: 31000,
    source: "Festival",
    assignedUserId: "user_manager",
    stageId: "stage_possible",
    tags: ["Event"],
    notes: "Need a recap film for the coastal food week.",
    lastNote: "Board meets Friday to pick a production partner.",
    createdAt: "2026-08-08",
  },
  {
    id: "co_quartzpine",
    clientNumber: "DW-1034",
    company: "Quartz & Pine Interiors",
    industry: "Design",
    name: "Helena Cho",
    email: "helena@quartzandpine.com",
    phone: "(503) 555-0190",
    potentialValue: 54000,
    source: "Referral",
    assignedUserId: "user_editor",
    stageId: "stage_paid",
    tags: ["Brand Campaign"],
    notes: "Showroom films for the Portland atelier.",
    lastNote: "Second invoice scheduled after the stills gallery.",
    createdAt: "2026-05-30",
  },
  {
    id: "co_nightorchard",
    clientNumber: "DW-1035",
    company: "Night Orchard Films",
    industry: "Film",
    name: "Marcus Bell",
    email: "marcus@nightorchard.film",
    phone: "(718) 555-0121",
    potentialValue: 38000,
    source: "Repeat inquiry",
    assignedUserId: "user_admin",
    stageId: "stage_trial",
    tags: ["Film"],
    notes: "Title sequence trial for their autumn feature.",
    lastNote: "They want a warmer grain and slower type.",
    createdAt: "2026-08-10",
  },
] as const;

export const DEMO_PROJECTS = [
  {
    id: "proj_solstice_short",
    name: "Solstice — Palmdale Short",
    clientId: "co_solstice",
    type: "Film",
    budget: 92000,
    deadline: "2026-10-18",
    status: "Pre-production",
    progress: 35,
    notes: "Scout complete. Cast callbacks next week.",
  },
  {
    id: "proj_quartz_showroom",
    name: "Quartz & Pine — Atelier Films",
    clientId: "co_quartzpine",
    type: "Brand Campaign",
    budget: 54000,
    deadline: "2026-09-12",
    status: "Production",
    progress: 62,
    notes: "Day two interiors wrapped. Exterior dawn shot remains.",
  },
] as const;

export const DEMO_PAYMENTS = [
  {
    id: "pay_solstice_deposit",
    date: "2026-07-02",
    clientId: "co_solstice",
    projectId: "proj_solstice_short",
    amount: 28000,
    status: "Paid",
    method: "Wire",
    invoiceNumber: "DW-INV-2401",
    notes: "Production deposit",
  },
  {
    id: "pay_quartz_1",
    date: "2026-06-18",
    clientId: "co_quartzpine",
    projectId: "proj_quartz_showroom",
    amount: 18000,
    status: "Paid",
    method: "ACH",
    invoiceNumber: "DW-INV-2394",
    notes: "First installment",
  },
  {
    id: "pay_quartz_2",
    date: "2026-08-22",
    clientId: "co_quartzpine",
    projectId: "proj_quartz_showroom",
    amount: 16000,
    status: "Pending",
    method: "ACH",
    invoiceNumber: "DW-INV-2410",
    notes: "Second installment",
  },
] as const;
